name: Release

on:
  push:
    tags:
      - 'v*'  # 例如 v1.0.0、v2.1.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. 取回程式碼
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. 設定 Go 環境
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 3. 編譯 Go 專案
      - name: Build binary
        run: |
          mkdir -p dist
          go build -o dist/server ./cmd/server/main.go

      # 4. 打包 zip
      - name: Package zip
        run: |
          cd dist
          zip server-${GITHUB_REF_NAME}.zip server

      # 5. 生成 release notes
      - name: Generate release notes
        id: generate_notes
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 ${GITHUB_REF}^)
          echo "Previous tag: $PREV_TAG"
          NOTES=$(git log $PREV_TAG..${GITHUB_REF} --pretty=format:'- %s' || echo "- Initial release")
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 6. 創建 GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: ${{ steps.generate_notes.outputs.notes }}
          draft: false
          prerelease: false
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
